import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MySession from "@/components/MySession/MySession";
import { CartProvider } from "@/Shared/context/CartContext";

const inter = Exo({ subsets: ["latin"], variable: "--font-exo" });

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body suppressHydrationWarning={true} className={`antialiased`}>
        <CartProvider>
          <MySession>
            <Navbar />
            <Toaster position="top-right" />
            {children}
            <Footer />
          </MySession>
        </CartProvider>
      </body>
    </html>
  );
}
